USE name_in_synonym;

INSERT INTO languages(language_name) VALUE ('english');
INSERT INTO languages(language_name) VALUE ('telugu');
INSERT INTO languages(language_name) VALUE ('hindi');

INSERT INTO words (word, language_id) VALUE ("amazing",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("incredible",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("unbelievable",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("improbable",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("fabulous",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("wonderful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("fantastic",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("astonishing",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("astounding",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("extraordinary",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("angry",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("mad",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("furious",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("enraged",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("excited",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("wrathful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("indignant",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("exasperated",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("aroused",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("inflamed",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("ask",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("question",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("demand",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("request",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("expect",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("inquire",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("query",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("interrogate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("examine",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("quiz",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("beautiful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("pretty",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("lovely",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("handsome",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("attractive",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("gorgeous",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("dazzling",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("splendid",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("magnificent",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("comely",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("fair",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("graceful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("elegant",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("fine",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("exquisite",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("aesthetic",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("pleasing",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("shapely",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("delicate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("stunning",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("glorious",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("heavenly",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("resplendent",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("radiant",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("glowing",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("blooming",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("sparkling",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("begin",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("start",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("open",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("launch",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("initiate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("commence",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("inaugurate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("originate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("cut",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("gash",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("slash",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("prick",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("nick",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("sever",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("slice",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("carve",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("cleave",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("slit",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("chop",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("crop",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("lop",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("reduce",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("difference",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("disagreement",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("inequity",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("contrast",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("dissimilarity",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("incompatibility",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("eager",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("keen",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("fervent",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("enthusiastic",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("involved",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("interested",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("just",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("impartial",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("unbiased",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("objective",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("honest",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("get",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("acquire",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("obtain",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("secure",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("procure",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("gain",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("fetch",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("find",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("score",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("accumulate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("win",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("earn",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("rep",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("catch",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("net",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("bag",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("derive",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("collect",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("gather",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("glean",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("pickup",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("accept",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("regain",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("salvage",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("happy",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("pleased",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("contented",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("satisfied",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("delighted",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("elated",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("joyful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("cheerful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("ecstatic",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("jubilant",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("glad",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("blissful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("overjoyed",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("idea",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("thought",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("concept",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("conception",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("notion",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("understanding",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("opinion",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("plan",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("view",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("belief",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("keep",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("hold",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("retain",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("withhold",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("preserve",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("maintain",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("sustain",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("support",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("lazy",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("indolent",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("slothful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("idle",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("inactive",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("sluggish",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("make",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("create",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("invent",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("form",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("construct",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("design",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("fabricate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("manufacture",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("produce",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("build",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("develop",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("do",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("effect",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("execute",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("compose",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("perform",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("accomplish",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("new",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("fresh",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("unique",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("original",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("unusual",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("novel",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("modern",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("current",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("recent",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("old",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("feeble",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("frail",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("ancient",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("weak",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("aged",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("used",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("worn",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("dilapidated",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("ragged",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("faded",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("former",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("passe",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("veteran",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("mature",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("venerable",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("primitive",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("traditional",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("archaic",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("conventional",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("customary",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("stale",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("musty",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("obsolete",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("extinct",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("popular",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("approved",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("accepted",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("favorite",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("celebrated",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("common",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("quiet",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("silent",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("still",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("soundless",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("mute",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("tranquil",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("peaceful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("calm",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("right",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("correct",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("accurate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("factual",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("true",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("good",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("upright",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("lawful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("moral",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("proper",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("suitable",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("apt",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("legal",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("stop",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("cease",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("stay",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("pause",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("discontinue",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("conclude",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("end",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("finish",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("quit",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("think",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("judge",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("deem",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("assume",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("believe",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("consider",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("contemplate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("reflect",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("mediate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("ugly",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("hideous",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("frightful",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("frightening",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("shocking",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("horrible",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("unpleasant",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("monstrous",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("terrifying",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("gross",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("grisly",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("ghastly",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("horrid",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("unsightly",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("plain",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("homely",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("evil",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("repulsive",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("gruesome",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("wrong",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("incorrect",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("inaccurate",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("mistaken",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("erroneous",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("improper",(SELECT language_id FROM languages WHERE language_name = 'english'));
INSERT INTO words (word, language_id) VALUE ("unsuitable",(SELECT language_id FROM languages WHERE language_name = 'english'));

INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "incredible" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "unbelievable" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "improbable" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fabulous" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "wonderful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fantastic" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "astonishing" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "astounding" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "extraordinary" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "mad" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "furious" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "enraged" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "excited" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "wrathful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "indignant" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "exasperated" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "aroused" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "inflamed" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "question" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "demand" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "request" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "expect" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "inquire" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "query" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "interrogate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "examine" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "quiz" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "pretty" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "lovely" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "handsome" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "attractive" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "gorgeous" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "dazzling" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "splendid" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "magnificent" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "comely" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fair" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "graceful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "elegant" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fine" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "exquisite" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "aesthetic" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "pleasing" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "shapely" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "delicate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "stunning" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "glorious" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "heavenly" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "resplendent" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "radiant" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "glowing" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "blooming" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "sparkling" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "start" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "open" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "launch" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "initiate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "commence" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "inaugurate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "originate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "gash" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "slash" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "prick" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "nick" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "sever" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "slice" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "carve" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "cleave" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "slit" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "chop" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "crop" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "lop" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "reduce" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "disagreement" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "inequity" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "contrast" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "dissimilarity" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "incompatibility" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "keen" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fervent" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "enthusiastic" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "involved" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "interested" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "just" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "impartial" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "unbiased" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "objective" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "honest" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "acquire" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "obtain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "secure" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "procure" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "gain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fetch" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "find" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "score" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "accumulate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "win" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "earn" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "rep" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "catch" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "net" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "bag" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "derive" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "collect" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "gather" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "glean" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "pickup" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "accept" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "regain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "salvage" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "pleased" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "contented" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "satisfied" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "delighted" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "elated" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "joyful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "cheerful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "ecstatic" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "jubilant" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "glad" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "blissful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "overjoyed" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "thought" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "concept" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "conception" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "notion" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "understanding" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "opinion" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "plan" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "view" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "belief" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "hold" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "retain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "withhold" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "preserve" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "maintain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "sustain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "support" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "indolent" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "slothful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "idle" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "inactive" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "sluggish" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "create" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "originate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "invent" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "form" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "construct" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "design" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fabricate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "manufacture" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "produce" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "build" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "develop" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "do" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "effect" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "execute" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "compose" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "perform" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "accomplish" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "earn" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "gain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "obtain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "acquire" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "get" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fresh" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "unique" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "original" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "unusual" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "novel" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "modern" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "current" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "recent" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "feeble" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "frail" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "ancient" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "weak" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "aged" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "used" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "worn" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "dilapidated" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "ragged" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "faded" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "former" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "passe" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "veteran" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "mature" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "venerable" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "primitive" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "traditional" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "archaic" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "conventional" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "customary" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "stale" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "musty" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "obsolete" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "extinct" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "approved" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "accepted" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "favorite" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "celebrated" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "common" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "current" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "silent" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "still" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "soundless" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "mute" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "tranquil" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "peaceful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "calm" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "correct" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "accurate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "factual" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "true" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "good" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "just" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "honest" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "upright" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "lawful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "moral" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "proper" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "suitable" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "apt" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "legal" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "fair" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "cease" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "stay" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "pause" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "discontinue" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "conclude" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "end" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "finish" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "quit" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "judge" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "deem" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "assume" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "believe" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "consider" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "contemplate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "reflect" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "mediate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "hideous" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "frightful" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "frightening" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "shocking" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "horrible" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "unpleasant" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "monstrous" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "terrifying" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "gross" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "grisly" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "ghastly" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "horrid" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "unsightly" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "plain" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "homely" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "evil" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "repulsive" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "gruesome" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "incorrect" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "inaccurate" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "mistaken" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "erroneous" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "improper" AND words.language_id = 1 LIMIT 1);
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong" AND words.language_id = 1 LIMIT 1), (SELECT word_id FROM words WHERE word = "unsuitable" AND words.language_id = 1 LIMIT 1);
