USE name_in_synonym;
INSERT INTO words (word, language) VALUE ("amazing", 'english');
INSERT INTO words (word, language) VALUE ("incredible", 'english');
INSERT INTO words (word, language) VALUE ("unbelievable", 'english');
INSERT INTO words (word, language) VALUE ("improbable", 'english');
INSERT INTO words (word, language) VALUE ("fabulous", 'english');
INSERT INTO words (word, language) VALUE ("wonderful", 'english');
INSERT INTO words (word, language) VALUE ("fantastic", 'english');
INSERT INTO words (word, language) VALUE ("astonishing", 'english');
INSERT INTO words (word, language) VALUE ("astounding", 'english');
INSERT INTO words (word, language) VALUE ("extraordinary", 'english');
INSERT INTO words (word, language) VALUE ("angry", 'english');
INSERT INTO words (word, language) VALUE ("mad", 'english');
INSERT INTO words (word, language) VALUE ("furious", 'english');
INSERT INTO words (word, language) VALUE ("enraged", 'english');
INSERT INTO words (word, language) VALUE ("excited", 'english');
INSERT INTO words (word, language) VALUE ("wrathful", 'english');
INSERT INTO words (word, language) VALUE ("indignant", 'english');
INSERT INTO words (word, language) VALUE ("exasperated", 'english');
INSERT INTO words (word, language) VALUE ("aroused", 'english');
INSERT INTO words (word, language) VALUE ("inflamed", 'english');
INSERT INTO words (word, language) VALUE ("ask", 'english');
INSERT INTO words (word, language) VALUE ("question", 'english');
INSERT INTO words (word, language) VALUE ("demand", 'english');
INSERT INTO words (word, language) VALUE ("request", 'english');
INSERT INTO words (word, language) VALUE ("expect", 'english');
INSERT INTO words (word, language) VALUE ("inquire", 'english');
INSERT INTO words (word, language) VALUE ("query", 'english');
INSERT INTO words (word, language) VALUE ("interrogate", 'english');
INSERT INTO words (word, language) VALUE ("examine", 'english');
INSERT INTO words (word, language) VALUE ("quiz", 'english');
INSERT INTO words (word, language) VALUE ("beautiful", 'english');
INSERT INTO words (word, language) VALUE ("pretty", 'english');
INSERT INTO words (word, language) VALUE ("lovely", 'english');
INSERT INTO words (word, language) VALUE ("handsome", 'english');
INSERT INTO words (word, language) VALUE ("attractive", 'english');
INSERT INTO words (word, language) VALUE ("gorgeous", 'english');
INSERT INTO words (word, language) VALUE ("dazzling", 'english');
INSERT INTO words (word, language) VALUE ("splendid", 'english');
INSERT INTO words (word, language) VALUE ("magnificent", 'english');
INSERT INTO words (word, language) VALUE ("comely", 'english');
INSERT INTO words (word, language) VALUE ("fair", 'english');
INSERT INTO words (word, language) VALUE ("graceful", 'english');
INSERT INTO words (word, language) VALUE ("elegant", 'english');
INSERT INTO words (word, language) VALUE ("fine", 'english');
INSERT INTO words (word, language) VALUE ("exquisite", 'english');
INSERT INTO words (word, language) VALUE ("aesthetic", 'english');
INSERT INTO words (word, language) VALUE ("pleasing", 'english');
INSERT INTO words (word, language) VALUE ("shapely", 'english');
INSERT INTO words (word, language) VALUE ("delicate", 'english');
INSERT INTO words (word, language) VALUE ("stunning", 'english');
INSERT INTO words (word, language) VALUE ("glorious", 'english');
INSERT INTO words (word, language) VALUE ("heavenly", 'english');
INSERT INTO words (word, language) VALUE ("resplendent", 'english');
INSERT INTO words (word, language) VALUE ("radiant", 'english');
INSERT INTO words (word, language) VALUE ("glowing", 'english');
INSERT INTO words (word, language) VALUE ("blooming", 'english');
INSERT INTO words (word, language) VALUE ("sparkling", 'english');
INSERT INTO words (word, language) VALUE ("begin", 'english');
INSERT INTO words (word, language) VALUE ("start", 'english');
INSERT INTO words (word, language) VALUE ("open", 'english');
INSERT INTO words (word, language) VALUE ("launch", 'english');
INSERT INTO words (word, language) VALUE ("initiate", 'english');
INSERT INTO words (word, language) VALUE ("commence", 'english');
INSERT INTO words (word, language) VALUE ("inaugurate", 'english');
INSERT INTO words (word, language) VALUE ("originate", 'english');
INSERT INTO words (word, language) VALUE ("cut", 'english');
INSERT INTO words (word, language) VALUE ("gash", 'english');
INSERT INTO words (word, language) VALUE ("slash", 'english');
INSERT INTO words (word, language) VALUE ("prick", 'english');
INSERT INTO words (word, language) VALUE ("nick", 'english');
INSERT INTO words (word, language) VALUE ("sever", 'english');
INSERT INTO words (word, language) VALUE ("slice", 'english');
INSERT INTO words (word, language) VALUE ("carve", 'english');
INSERT INTO words (word, language) VALUE ("cleave", 'english');
INSERT INTO words (word, language) VALUE ("slit", 'english');
INSERT INTO words (word, language) VALUE ("chop", 'english');
INSERT INTO words (word, language) VALUE ("crop", 'english');
INSERT INTO words (word, language) VALUE ("lop", 'english');
INSERT INTO words (word, language) VALUE ("reduce", 'english');
INSERT INTO words (word, language) VALUE ("difference", 'english');
INSERT INTO words (word, language) VALUE ("disagreement", 'english');
INSERT INTO words (word, language) VALUE ("inequity", 'english');
INSERT INTO words (word, language) VALUE ("contrast", 'english');
INSERT INTO words (word, language) VALUE ("dissimilarity", 'english');
INSERT INTO words (word, language) VALUE ("incompatibility", 'english');
INSERT INTO words (word, language) VALUE ("eager", 'english');
INSERT INTO words (word, language) VALUE ("keen", 'english');
INSERT INTO words (word, language) VALUE ("fervent", 'english');
INSERT INTO words (word, language) VALUE ("enthusiastic", 'english');
INSERT INTO words (word, language) VALUE ("involved", 'english');
INSERT INTO words (word, language) VALUE ("interested", 'english');
INSERT INTO words (word, language) VALUE ("just", 'english');
INSERT INTO words (word, language) VALUE ("impartial", 'english');
INSERT INTO words (word, language) VALUE ("unbiased", 'english');
INSERT INTO words (word, language) VALUE ("objective", 'english');
INSERT INTO words (word, language) VALUE ("honest", 'english');
INSERT INTO words (word, language) VALUE ("get", 'english');
INSERT INTO words (word, language) VALUE ("acquire", 'english');
INSERT INTO words (word, language) VALUE ("obtain", 'english');
INSERT INTO words (word, language) VALUE ("secure", 'english');
INSERT INTO words (word, language) VALUE ("procure", 'english');
INSERT INTO words (word, language) VALUE ("gain", 'english');
INSERT INTO words (word, language) VALUE ("fetch", 'english');
INSERT INTO words (word, language) VALUE ("find", 'english');
INSERT INTO words (word, language) VALUE ("score", 'english');
INSERT INTO words (word, language) VALUE ("accumulate", 'english');
INSERT INTO words (word, language) VALUE ("win", 'english');
INSERT INTO words (word, language) VALUE ("earn", 'english');
INSERT INTO words (word, language) VALUE ("rep", 'english');
INSERT INTO words (word, language) VALUE ("catch", 'english');
INSERT INTO words (word, language) VALUE ("net", 'english');
INSERT INTO words (word, language) VALUE ("bag", 'english');
INSERT INTO words (word, language) VALUE ("derive", 'english');
INSERT INTO words (word, language) VALUE ("collect", 'english');
INSERT INTO words (word, language) VALUE ("gather", 'english');
INSERT INTO words (word, language) VALUE ("glean", 'english');
INSERT INTO words (word, language) VALUE ("pickup", 'english');
INSERT INTO words (word, language) VALUE ("accept", 'english');
INSERT INTO words (word, language) VALUE ("regain", 'english');
INSERT INTO words (word, language) VALUE ("salvage", 'english');
INSERT INTO words (word, language) VALUE ("happy", 'english');
INSERT INTO words (word, language) VALUE ("pleased", 'english');
INSERT INTO words (word, language) VALUE ("contented", 'english');
INSERT INTO words (word, language) VALUE ("satisfied", 'english');
INSERT INTO words (word, language) VALUE ("delighted", 'english');
INSERT INTO words (word, language) VALUE ("elated", 'english');
INSERT INTO words (word, language) VALUE ("joyful", 'english');
INSERT INTO words (word, language) VALUE ("cheerful", 'english');
INSERT INTO words (word, language) VALUE ("ecstatic", 'english');
INSERT INTO words (word, language) VALUE ("jubilant", 'english');
INSERT INTO words (word, language) VALUE ("glad", 'english');
INSERT INTO words (word, language) VALUE ("blissful", 'english');
INSERT INTO words (word, language) VALUE ("overjoyed", 'english');
INSERT INTO words (word, language) VALUE ("idea", 'english');
INSERT INTO words (word, language) VALUE ("thought", 'english');
INSERT INTO words (word, language) VALUE ("concept", 'english');
INSERT INTO words (word, language) VALUE ("conception", 'english');
INSERT INTO words (word, language) VALUE ("notion", 'english');
INSERT INTO words (word, language) VALUE ("understanding", 'english');
INSERT INTO words (word, language) VALUE ("opinion", 'english');
INSERT INTO words (word, language) VALUE ("plan", 'english');
INSERT INTO words (word, language) VALUE ("view", 'english');
INSERT INTO words (word, language) VALUE ("belief", 'english');
INSERT INTO words (word, language) VALUE ("keep", 'english');
INSERT INTO words (word, language) VALUE ("hold", 'english');
INSERT INTO words (word, language) VALUE ("retain", 'english');
INSERT INTO words (word, language) VALUE ("withhold", 'english');
INSERT INTO words (word, language) VALUE ("preserve", 'english');
INSERT INTO words (word, language) VALUE ("maintain", 'english');
INSERT INTO words (word, language) VALUE ("sustain", 'english');
INSERT INTO words (word, language) VALUE ("support", 'english');
INSERT INTO words (word, language) VALUE ("lazy", 'english');
INSERT INTO words (word, language) VALUE ("indolent", 'english');
INSERT INTO words (word, language) VALUE ("slothful", 'english');
INSERT INTO words (word, language) VALUE ("idle", 'english');
INSERT INTO words (word, language) VALUE ("inactive", 'english');
INSERT INTO words (word, language) VALUE ("sluggish", 'english');
INSERT INTO words (word, language) VALUE ("make", 'english');
INSERT INTO words (word, language) VALUE ("create", 'english');
INSERT INTO words (word, language) VALUE ("invent", 'english');
INSERT INTO words (word, language) VALUE ("form", 'english');
INSERT INTO words (word, language) VALUE ("construct", 'english');
INSERT INTO words (word, language) VALUE ("design", 'english');
INSERT INTO words (word, language) VALUE ("fabricate", 'english');
INSERT INTO words (word, language) VALUE ("manufacture", 'english');
INSERT INTO words (word, language) VALUE ("produce", 'english');
INSERT INTO words (word, language) VALUE ("build", 'english');
INSERT INTO words (word, language) VALUE ("develop", 'english');
INSERT INTO words (word, language) VALUE ("do", 'english');
INSERT INTO words (word, language) VALUE ("effect", 'english');
INSERT INTO words (word, language) VALUE ("execute", 'english');
INSERT INTO words (word, language) VALUE ("compose", 'english');
INSERT INTO words (word, language) VALUE ("perform", 'english');
INSERT INTO words (word, language) VALUE ("accomplish", 'english');
INSERT INTO words (word, language) VALUE ("new", 'english');
INSERT INTO words (word, language) VALUE ("fresh", 'english');
INSERT INTO words (word, language) VALUE ("unique", 'english');
INSERT INTO words (word, language) VALUE ("original", 'english');
INSERT INTO words (word, language) VALUE ("unusual", 'english');
INSERT INTO words (word, language) VALUE ("novel", 'english');
INSERT INTO words (word, language) VALUE ("modern", 'english');
INSERT INTO words (word, language) VALUE ("current", 'english');
INSERT INTO words (word, language) VALUE ("recent", 'english');
INSERT INTO words (word, language) VALUE ("old", 'english');
INSERT INTO words (word, language) VALUE ("feeble", 'english');
INSERT INTO words (word, language) VALUE ("frail", 'english');
INSERT INTO words (word, language) VALUE ("ancient", 'english');
INSERT INTO words (word, language) VALUE ("weak", 'english');
INSERT INTO words (word, language) VALUE ("aged", 'english');
INSERT INTO words (word, language) VALUE ("used", 'english');
INSERT INTO words (word, language) VALUE ("worn", 'english');
INSERT INTO words (word, language) VALUE ("dilapidated", 'english');
INSERT INTO words (word, language) VALUE ("ragged", 'english');
INSERT INTO words (word, language) VALUE ("faded", 'english');
INSERT INTO words (word, language) VALUE ("former", 'english');
INSERT INTO words (word, language) VALUE ("passe", 'english');
INSERT INTO words (word, language) VALUE ("veteran", 'english');
INSERT INTO words (word, language) VALUE ("mature", 'english');
INSERT INTO words (word, language) VALUE ("venerable", 'english');
INSERT INTO words (word, language) VALUE ("primitive", 'english');
INSERT INTO words (word, language) VALUE ("traditional", 'english');
INSERT INTO words (word, language) VALUE ("archaic", 'english');
INSERT INTO words (word, language) VALUE ("conventional", 'english');
INSERT INTO words (word, language) VALUE ("customary", 'english');
INSERT INTO words (word, language) VALUE ("stale", 'english');
INSERT INTO words (word, language) VALUE ("musty", 'english');
INSERT INTO words (word, language) VALUE ("obsolete", 'english');
INSERT INTO words (word, language) VALUE ("extinct", 'english');
INSERT INTO words (word, language) VALUE ("popular", 'english');
INSERT INTO words (word, language) VALUE ("approved", 'english');
INSERT INTO words (word, language) VALUE ("accepted", 'english');
INSERT INTO words (word, language) VALUE ("favorite", 'english');
INSERT INTO words (word, language) VALUE ("celebrated", 'english');
INSERT INTO words (word, language) VALUE ("common", 'english');
INSERT INTO words (word, language) VALUE ("quiet", 'english');
INSERT INTO words (word, language) VALUE ("silent", 'english');
INSERT INTO words (word, language) VALUE ("still", 'english');
INSERT INTO words (word, language) VALUE ("soundless", 'english');
INSERT INTO words (word, language) VALUE ("mute", 'english');
INSERT INTO words (word, language) VALUE ("tranquil", 'english');
INSERT INTO words (word, language) VALUE ("peaceful", 'english');
INSERT INTO words (word, language) VALUE ("calm", 'english');
INSERT INTO words (word, language) VALUE ("right", 'english');
INSERT INTO words (word, language) VALUE ("correct", 'english');
INSERT INTO words (word, language) VALUE ("accurate", 'english');
INSERT INTO words (word, language) VALUE ("factual", 'english');
INSERT INTO words (word, language) VALUE ("true", 'english');
INSERT INTO words (word, language) VALUE ("good", 'english');
INSERT INTO words (word, language) VALUE ("upright", 'english');
INSERT INTO words (word, language) VALUE ("lawful", 'english');
INSERT INTO words (word, language) VALUE ("moral", 'english');
INSERT INTO words (word, language) VALUE ("proper", 'english');
INSERT INTO words (word, language) VALUE ("suitable", 'english');
INSERT INTO words (word, language) VALUE ("apt", 'english');
INSERT INTO words (word, language) VALUE ("legal", 'english');
INSERT INTO words (word, language) VALUE ("stop", 'english');
INSERT INTO words (word, language) VALUE ("cease", 'english');
INSERT INTO words (word, language) VALUE ("stay", 'english');
INSERT INTO words (word, language) VALUE ("pause", 'english');
INSERT INTO words (word, language) VALUE ("discontinue", 'english');
INSERT INTO words (word, language) VALUE ("conclude", 'english');
INSERT INTO words (word, language) VALUE ("end", 'english');
INSERT INTO words (word, language) VALUE ("finish", 'english');
INSERT INTO words (word, language) VALUE ("quit", 'english');
INSERT INTO words (word, language) VALUE ("think", 'english');
INSERT INTO words (word, language) VALUE ("judge", 'english');
INSERT INTO words (word, language) VALUE ("deem", 'english');
INSERT INTO words (word, language) VALUE ("assume", 'english');
INSERT INTO words (word, language) VALUE ("believe", 'english');
INSERT INTO words (word, language) VALUE ("consider", 'english');
INSERT INTO words (word, language) VALUE ("contemplate", 'english');
INSERT INTO words (word, language) VALUE ("reflect", 'english');
INSERT INTO words (word, language) VALUE ("mediate", 'english');
INSERT INTO words (word, language) VALUE ("ugly", 'english');
INSERT INTO words (word, language) VALUE ("hideous", 'english');
INSERT INTO words (word, language) VALUE ("frightful", 'english');
INSERT INTO words (word, language) VALUE ("frightening", 'english');
INSERT INTO words (word, language) VALUE ("shocking", 'english');
INSERT INTO words (word, language) VALUE ("horrible", 'english');
INSERT INTO words (word, language) VALUE ("unpleasant", 'english');
INSERT INTO words (word, language) VALUE ("monstrous", 'english');
INSERT INTO words (word, language) VALUE ("terrifying", 'english');
INSERT INTO words (word, language) VALUE ("gross", 'english');
INSERT INTO words (word, language) VALUE ("grisly", 'english');
INSERT INTO words (word, language) VALUE ("ghastly", 'english');
INSERT INTO words (word, language) VALUE ("horrid", 'english');
INSERT INTO words (word, language) VALUE ("unsightly", 'english');
INSERT INTO words (word, language) VALUE ("plain", 'english');
INSERT INTO words (word, language) VALUE ("homely", 'english');
INSERT INTO words (word, language) VALUE ("evil", 'english');
INSERT INTO words (word, language) VALUE ("repulsive", 'english');
INSERT INTO words (word, language) VALUE ("gruesome", 'english');
INSERT INTO words (word, language) VALUE ("wrong", 'english');
INSERT INTO words (word, language) VALUE ("incorrect", 'english');
INSERT INTO words (word, language) VALUE ("inaccurate", 'english');
INSERT INTO words (word, language) VALUE ("mistaken", 'english');
INSERT INTO words (word, language) VALUE ("erroneous", 'english');
INSERT INTO words (word, language) VALUE ("improper", 'english');
INSERT INTO words (word, language) VALUE ("unsuitable", 'english');

INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "incredible"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "unbelievable"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "improbable"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fabulous"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "wonderful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fantastic"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "astonishing"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "astounding"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "amazing"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "extraordinary"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "mad"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "furious"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "enraged"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "excited"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "wrathful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "indignant"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "exasperated"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "aroused"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "angry"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "inflamed"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "question"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "demand"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "request"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "expect"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "inquire"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "query"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "interrogate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "examine"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ask"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "quiz"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "pretty"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "lovely"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "handsome"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "attractive"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "gorgeous"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "dazzling"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "splendid"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "magnificent"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "comely"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fair"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "graceful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "elegant"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fine"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "exquisite"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "aesthetic"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "pleasing"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "shapely"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "delicate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "stunning"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "glorious"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "heavenly"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "resplendent"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "radiant"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "glowing"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "blooming"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "beautiful"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "sparkling"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "start"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "open"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "launch"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "initiate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "commence"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "inaugurate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "begin"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "originate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "gash"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "slash"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "prick"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "nick"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "sever"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "slice"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "carve"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "cleave"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "slit"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "chop"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "crop"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "lop"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "cut"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "reduce"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "disagreement"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "inequity"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "contrast"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "dissimilarity"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "difference"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "incompatibility"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "keen"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fervent"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "enthusiastic"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "involved"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "eager"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "interested"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "just"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "impartial"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "unbiased"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "objective"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "fair"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "honest"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "acquire"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "obtain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "secure"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "procure"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "gain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fetch"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "find"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "score"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "accumulate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "win"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "earn"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "rep"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "catch"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "net"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "bag"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "derive"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "collect"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "gather"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "glean"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "pickup"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "accept"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "regain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "salvage"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "pleased"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "contented"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "satisfied"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "delighted"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "elated"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "joyful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "cheerful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "ecstatic"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "jubilant"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "glad"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "blissful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "happy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "overjoyed"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "thought"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "concept"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "conception"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "notion"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "understanding"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "opinion"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "plan"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "view"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "idea"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "belief"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "hold"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "retain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "withhold"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "preserve"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "maintain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "sustain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "keep"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "support"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "indolent"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "slothful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "idle"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "inactive"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "lazy"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "sluggish"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "create"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "originate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "invent"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "form"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "construct"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "design"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fabricate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "manufacture"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "produce"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "build"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "develop"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "do"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "effect"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "execute"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "compose"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "perform"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "accomplish"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "earn"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "gain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "obtain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "acquire"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "make"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "get"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fresh"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "unique"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "original"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "unusual"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "novel"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "modern"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "current"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "new"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "recent"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "feeble"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "frail"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "ancient"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "weak"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "aged"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "used"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "worn"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "dilapidated"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "ragged"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "faded"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "former"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "passe"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "veteran"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "mature"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "venerable"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "primitive"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "traditional"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "archaic"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "conventional"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "customary"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "stale"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "musty"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "obsolete"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "old"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "extinct"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "approved"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "accepted"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "favorite"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "celebrated"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "common"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "popular"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "current"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "silent"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "still"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "soundless"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "mute"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "tranquil"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "peaceful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "quiet"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "calm"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "correct"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "accurate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "factual"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "true"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "good"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "just"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "honest"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "upright"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "lawful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "moral"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "proper"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "suitable"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "apt"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "legal"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "right"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "fair"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "cease"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "stay"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "pause"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "discontinue"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "conclude"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "end"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "finish"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "stop"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "quit"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "judge"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "deem"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "assume"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "believe"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "consider"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "contemplate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "reflect"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "think"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "mediate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "hideous"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "frightful"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "frightening"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "shocking"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "horrible"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "unpleasant"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "monstrous"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "terrifying"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "gross"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "grisly"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "ghastly"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "horrid"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "unsightly"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "plain"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "homely"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "evil"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "repulsive"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "ugly"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "gruesome"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "incorrect"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "inaccurate"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "mistaken"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "erroneous"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "improper"AND words.language = 'english' LIMIT 1) AS word_2;
INSERT INTO pair (word_1, word_2) SELECT(SELECT word_id FROM words WHERE word = "wrong"AND words.language = 'english' LIMIT 1) AS word_1, (SELECT word_id FROM words WHERE word = "unsuitable"AND words.language = 'english' LIMIT 1) AS word_2;
